---
title: "priprava_na_zapocet"
output:
  html_document:
    #toc: yes
    toc_depth: 3
    toc_float:
      collapsed: yes
      smooth_scroll: yes
  pdf_document: default
  word_document: default
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	#echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

```{r echo=FALSE, results='asis'}
if(knitr::opts_chunk$get()$echo) cat("\n\n## Načtení knihoven\n\n")
```


```{r Nacteni knihoven}
library(readxl)
library(dplyr)
library(ggplot2)
library(DescTools)
library(psych)
```

```{r}

```

```{r}
#Príklad 0
#Nakreslite pravdepodobnostnú funkciu (pmf) a distribučnú funkciu (cdf) náhodných veličín, ktoré sa
#vyskytujú v príkladoch 2, 3, 6 a 16. Na aké rozdelenie poukazuje graf pmf vzhľadom na (a)symetriu?
#Vypočítajte strednú hodnotu, smerodajnú odchýlku a varianciu týchto náhodných veličín
#a interpretujte ich. 



```


```{r}

#Príklad 1
#Zásielka 1000 výrobkov obsahuje 15 % nekvalitných výrobkov. Náhodne s vrátením vyberieme štyri
#výrobky. Určite pravdepodobnosť, že práve tri z nich budú kvalitné. Vypočítajte túto
#pravdepodobnosť, keď výbery realizujeme bez vrátenia. (0.368475; 0.369388) 


#1000 výrobků -> diskrétní proměnná
#počty neuspechu == 15% nekvalitnich vyrobku .. 

p1 <- dhyper(3, 850, 150, 4)  #bez vracení .. 0,15*1000 = 150 .. 1000-150 = 850 ... POČET VYROBKU-PROCENTA... počet vybranych vyrobku
cat("bez vrácení, známé počty kusů (chceme 3 kvalitní, uspech je 850 vyrobků a neuspech 150 vyrobku-.. vyber ze 4.. jaká bude. pravdepodobnost že ty 3 ze 4 budou PŘI NEVRACENÍ DO ´KRABICE ´ kvalitní je ): ",p1)

cat("\n")

p2 <- dbinom(3, 4, 0.85)  #s vracenim .. pravdepodobnost uspechu je 0,85 .. počet vybraných vyrobků
cat("s vrácením, známá pravděpodobnost (CHCEME 3 funkční, vybirame ze 4. pravdepodobnost je 0.85% uspesnych .. ´kontrolovane vracime zpet do seznamu´ ",p2)



```


```{r}
#Príklad 2

#Student má potíže se vstáváním. Za posledních 375 dní nebyl schopen vstát na zazvonění budíku ve 120 případech a nestihl své ranní povinnosti. V semestru #je 13 přednášek. Určete pravděpodobnost, že student:
#a) nestihne většinu přednášek,
#b) zaspí nejvýše dvakrát,
#c) stihne všechny přednášky,
#d) nestihne žádnou přednášku.

#Postup pro a) -> nestihne většinu přednášek .. nestihne víc jak 50% z 13 přednášek .. (zaspal 120x z 375 dní)
#zaspání = nějaký % počet x z 13 přednášek .. pravděpodobnost zaspání = 120/375
#určit p .. 50+% z 13 = 7 přednášek

x <- 6
počet_přednasek = 13
pravdepodobnost_zaspani <- 120/375
p_a <- pbinom(x,13,pravdepodobnost_zaspani)
cat("Pravděpodobnost, že student nestihne většinu přednášek je: ", p_a*100 , "%")

cat("\n")

p_b <- pbinom(2,13,pravdepodobnost_zaspani)
cat("Pravděpodobnost, že student zaspí nejvýše dvakrat je: ", p_b*100 , "%")

cat("\n")

#dbinom(2, 13, p)   # P(X = 2)
#pbinom(2, 13, p)   # P(X ≤ 2)




p_c <- dbinom(0,13,pravdepodobnost_zaspani)
cat("Pravděpodobnost, že student stihne všechny přednášky je: ", p_c*100 , "%")

cat("\n")

p_d <- dbinom(13,13, pravdepodobnost_zaspani)
cat("Pravděpodobnost, že student nestihne žádnou přednášku je: ", p_d*100 , "%")



```


```{r}


#**Příklad 3**
#Personalista ví, že o určitou účetní pozici ve firmě projeví zájem uchazeč s ekonomickým vysokoškolským vzděláním s pravděpodobností 0,65 a uchazeč #bez odpovídajícího ekonomického vzdělání s pravděpodobností 0,35. Určete pravděpodobnost, že **až čtvrtý uchazeč** o danou pozici bude mít #ekonomické vysokoškolské vzdělání. *(0,02787)*


#JEDNA SE O TYP POČET POKUSU D OPRVNIHO USPECHU.. POUZIJEME DGEOM

pravdepodobnost_vzdelani <- 0.65
#mame 0.65 usopechgu a 0.35 neuspechu my chceme spocitat jaka je pravdepodobnost ze bude mit odpovidajici vzdelani


#dgeom(k, p) = P( k neúspěchů PŘED prvním úspěchem )


p <- dgeom(3,pravdepodobnost_vzdelani)

p


```
```{r}

#**Příklad 6**
#Realitní makléř jedná v průměru s 5 zákazníky za den. Jaká je pravděpodobnost, že počet zákazníků makléře za jeden den
#a) bude **právě 5**,
#b) bude **větší než 4**.
#*(a) 0,1755; b) 0,5595)*



#je to za den ttakže jednotu času == poissnovo.. zkusíme ho udělat jako 1 a kdyžtak 24 

lambda <- 5 #V PRŮMĚRU 5 ZÁKAZNÍKŮ ZA DEN

p_a <- dpois(5, lambda)

cat("Pravděpodobnost, že počet zákazníků bude přesně 5", p_a*100, "%")

#druhe bude trochu jiné ... máme tam větší než.. tudíž musíme udělat 1-naše funkce

cat("\n")

p_b <- 1 - ppois(4, lambda)

cat("Pravděpodobnost, že počet zákazníků větší než 4", p_b*100 , "%")


```

```{r}
#Příklad 16 ()

#Ve výboru je 25 členů, z toho 15 hlasuje „pro“ a 10 „proti“.
#Náhodně je vybráno 5 členů.

#Určete pravděpodobnost, že:
#a) právě 3 z vybraných budou hlasovat „pro“,
#b) nejvýše 2 budou hlasovat „pro“,
#c) alespoň 4 budou hlasovat „pro“.


#JSOU ZNÁME POČTY PRO A PROTI.. TO ZNÍ JAKO HYPERGEOMETICKÉ

pro <- 15
proti <- 10

celkem <- pro+proti

výběr <- 3 #potom nejvyse 2 a potom alespon 4

vybraní_členi <- 5

p_a <- dhyper(pravdepodonost_vyberu, pro, proti, vybraní_členi)


cat("Pravděpodobnost, že právě 3 ze zvolených hlasovali PRO:", p_a*100,"%", "\n")

výběr <- 2 
p_b = phyper(výběr,pro,proti,vybraní_členi)

cat("Pravděpodobnost, že nějvýše dva ze zvolených hlasovali PRO:", p_b*100,"%", "\n")


výběr <- 4

p_c <- 1 - phyper(výběr-1, pro, proti, vybraní_členi)


cat("Pravděpodobnost, že alespoň čtyři ze zvolených hlasovali PRO:", p_c*100,"%" ,"\n")



```


```{r}

```















